apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
    service.beta.kubernetes.io/aws-load-balancer-type: external
  name: toktok-service
  namespace: 101toktok
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 3000
  selector:
    app: 101toktok-app
  type: LoadBalancer

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: toktok-service-account
  namespace: 101toktok
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::124718958862:role/eks-kubesystem-toktok-101

---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: 101toktok
  name: 101toktok-app
spec:
  selector:
    matchLabels:
      app: 101toktok-app
  replicas: 1
  template:
    metadata:
      labels:
        app: 101toktok-app
    spec:
      serviceAccountName: toktok-service-account
      containers:
        - image: 124718958862.dkr.ecr.us-east-1.amazonaws.com/toktok/openweather:1.0.2
          imagePullPolicy: Always
          name: 101toktok-app
          resources:
            requests:
              cpu: "0.5"
              memory: "128M"
            limits:
              cpu: "1"
              memory: "512M"
          ports:
            - containerPort: 3000

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: toktok-hpa
  namespace: 101toktok
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: 101toktok-app 
  minReplicas: 1
  maxReplicas: 8
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 120  # Target CPU utilization (%)
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 120 


########### This implement use AWSLB controller and Service with type 'LoadBalancer'
########### helm - https://artifacthub.io/packages/helm/aws/aws-load-balancer-controller
